import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'ta';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const translations = {
  en: {
    // Login Page
    "login.title": "Tamil Nadu",
    "login.subtitle": "Click2Ration",
    "login.tagline": "Simple. Secure. Convenient.",
    "login.heading": "Secure Login",
    "login.description": "Enter your ration card number and registered mobile number",
    "login.rationCard": "Ration Card Number",
    "login.rationCardPlaceholder": "Enter 12-digit ration card number",
    "login.mobile": "Mobile Number",
    "login.mobilePlaceholder": "Enter registered mobile number",
    "login.button": "Login & Verify",
    "login.verifying": "Verifying...",
    "login.security": "Protected by government security protocols",
    "login.encrypted": "End-to-end encrypted",
    "login.help": "Need help? Contact your local ration dealer",
    "login.helpline": "Helpline: 1967 (Toll Free)",
    "login.demoAccounts": "Demo Accounts:",
    "login.members": "members",
    
    // OTP Page
    "otp.title": "OTP Verification",
    "otp.description": "We've sent an OTP to your registered mobile",
    "otp.heading": "Enter OTP",
    "otp.sentTo": "OTP sent to",
    "otp.resendIn": "Resend OTP in",
    "otp.resend": "Resend OTP",
    "otp.familyMembers": "Family Members",
    "otp.selectMember": "Select the family member who will receive this ration order",
    "otp.memberSelected": "member selected for ration order",
    "otp.pleaseSelect": "Please select a family member",
    "otp.confirm": "Confirm & Continue",
    "otp.verifying": "Verifying...",
    "otp.male": "Male",
    "otp.female": "Female",
    "otp.years": "years",
    
    // Dashboard
    "dashboard.title": "Dashboard",
    "dashboard.welcome": "Welcome back",
    "dashboard.members": "members",
    "dashboard.backToLogin": "← Back to Login",
    "dashboard.availableItems": "Available Items",
    "dashboard.deliveryTime": "Delivery Time",
    "dashboard.currentMonth": "Current Month",
    "dashboard.deliveryAddress": "Delivery Address",
    "dashboard.home": "Home",
    "dashboard.commodities": "Available Commodities",
    "dashboard.allocation": "Your monthly allocation and consumption",
    "dashboard.available": "Available",
    "dashboard.outOfStock": "Out of Stock",
    "dashboard.remaining": "remaining",
    "dashboard.selectProducts": "Select Products & Order",
    "dashboard.recentOrders": "Recent Orders",
    "dashboard.purchaseHistory": "Your purchase history",
    "dashboard.delivered": "Delivered",
    "dashboard.deliveryInfo": "Delivery Information",
    "dashboard.nextSlot": "Next Available Slot",
    "dashboard.today": "Today",
    "dashboard.biometricRequired": "Biometric verification required at delivery",
    "dashboard.secureDelivery": "Secure delivery with fingerprint authentication",
    
    // Product Selection
    "products.title": "Select Products",
    "products.description": "Choose items and quantities for delivery",
    "products.quantity": "Quantity:",
    "products.default": "Default:",
    "products.available": "Available:",
    "products.orderSummary": "Order Summary",
    "products.reviewItems": "Review your selected items",
    "products.noItems": "No items selected",
    "products.chooseProducts": "Choose products to add to your order",
    "products.totalAmount": "Total Amount:",
    "products.proceedToPayment": "Proceed to Payment",
    "products.highQuality": "High quality rice for daily consumption",
    "products.nutritious": "Nutritious whole wheat flour",
    "products.pureRefined": "Pure refined sugar",
    "products.refinedPalm": "Refined palm oil for cooking",
    "products.highProtein": "High protein toor dhal",
    "products.iodized": "Iodized salt for health",
    
    // Order Confirmation
    "order.title": "Order Confirmation",
    "order.description": "Review and confirm your ration order",
    "order.deliveryAddress": "Delivery Address",
    "order.selectTime": "Select Delivery Time",
    "order.preferredSlot": "Choose your preferred delivery slot for today",
    "order.morning": "Morning",
    "order.afternoon": "Afternoon",
    "order.evening": "Evening",
    "order.unavailable": "Unavailable",
    "order.paymentMethod": "Payment Method",
    "order.paymentOption": "Choose your preferred payment option",
    "order.upiPayment": "UPI Payment",
    "order.upiDescription": "Pay using UPI apps",
    "order.card": "Debit/Credit Card",
    "order.cardDescription": "Secure card payment",
    "order.cash": "Cash on Delivery",
    "order.cashDescription": "Pay when you receive",
    "order.biometricVerification": "Biometric Verification Required",
    "order.biometricDescription": "For security, you'll need to provide fingerprint authentication when the delivery arrives at your doorstep.",
    "order.biometricBenefit1": "Ensures only authorized recipients receive rations",
    "order.biometricBenefit2": "Prevents fraud and unauthorized access",
    "order.biometricBenefit3": "Quick and secure verification process",
    "order.orderSummary": "Order Summary",
    "order.subtotal": "Subtotal",
    "order.deliveryFee": "Delivery Fee (Distance > 5km)",
    "order.total": "Total",
    "order.confirmOrder": "Confirm Order",
    "order.processing": "Processing Order...",
    "order.protected": "Your order is protected by government security",
    "order.smsUpdates": "You'll receive SMS updates on delivery",
    
    // Tracking Page
    "tracking.title": "Track Your Order",
    "tracking.description": "Real-time delivery updates",
    "tracking.order": "Order",
    "tracking.deliveryProgress": "Delivery Progress",
    "tracking.onTheWay": "on the way",
    "tracking.readyForDelivery": "ready for delivery",
    "tracking.overallProgress": "Overall Progress",
    "tracking.orderConfirmed": "Order Confirmed",
    "tracking.orderConfirmedDesc": "Your order has been confirmed and is being prepared",
    "tracking.itemsPrepared": "Items Prepared",
    "tracking.itemsPreparedDesc": "All items have been packed and ready for dispatch",
    "tracking.outForDelivery": "Out for Delivery",
    "tracking.outForDeliveryDesc": "Delivery agent is on the way to your location",
    "tracking.biometricVerification": "Biometric Verification",
    "tracking.biometricDesc": "Awaiting fingerprint verification for secure delivery",
    "tracking.expected": "Expected:",
    "tracking.enRoute": "En route to delivery",
    "tracking.liveLocation": "Live Location",
    "tracking.vehicleLocation": "Delivery Vehicle Location",
    "tracking.approximately": "Approximately",
    "tracking.away": "away",
    "tracking.eta": "ETA:",
    "tracking.minutes": "minutes",
    "tracking.deliveryAgent": "Delivery Agent",
    "tracking.contact": "Contact:",
    "tracking.vehicle": "Vehicle:",
    "tracking.orderDetails": "Order Details",
    "tracking.totalPaid": "Total Paid",
    "tracking.paymentMethod": "Payment Method:",
    "tracking.biometricSecurity": "Biometric Security",
    "tracking.secureDelivery": "Secure delivery requires fingerprint verification when the agent arrives.",
    "tracking.preventsUnauthorized": "Prevents unauthorized access",
    "tracking.ensuresRecipient": "Ensures proper recipient",
    "tracking.quickVerification": "Quick verification process",
    "tracking.readyForVerification": "Ready for Verification",
    "tracking.downloadReceipt": "Download Receipt",
    "tracking.returnToDashboard": "Return to Dashboard",
    
    // Product Names
    "product.rice": "Premium Rice",
    "product.wheat": "Whole Wheat",
    "product.sugar": "Refined Sugar",
    "product.oil": "Palm Oil",
    "product.dhal": "Toor Dhal",
    "product.salt": "Iodized Salt",
  },
  ta: {
    // Login Page
    "login.title": "தமிழ்நாடு",
    "login.subtitle": "கிளிக்2ரேஷன்",
    "login.tagline": "எளிது. பாதுகாப்பானது. வசதியானது.",
    "login.heading": "பாதுகாப்பான உள்நுழைவு",
    "login.description": "உங்கள் ரேஷன் அட்டை எண் மற்றும் பதிவு செய்யப்பட்ட மொபைல் எண்ணை உள்ளிடவும்",
    "login.rationCard": "ரேஷன் அட்டை எண்",
    "login.rationCardPlaceholder": "12 இலக்க ரேஷன் அட்டை எண்ணை உள்ளிடவும்",
    "login.mobile": "மொபைல் எண்",
    "login.mobilePlaceholder": "பதிவு செய்யப்பட்ட மொபைல் எண்ணை உள்ளிடவும்",
    "login.button": "உள்நுழைய & சரிபார்க்க",
    "login.verifying": "சரிபார்க்கப்படுகிறது...",
    "login.security": "அரசாங்க பாதுகாப்பு நெறிமுறைகளால் பாதுகாக்கப்படுகிறது",
    "login.encrypted": "முழு என்க்ரிப்ட் செய்யப்பட்டது",
    "login.help": "உதவி தேவையா? உங்கள் உள்ளூர் ரேஷன் விற்பனையாளரை தொடர்பு கொள்ளவும்",
    "login.helpline": "உதவி எண்: 1967 (இலவச)",
    "login.demoAccounts": "டெமோ கணக்குகள்:",
    "login.members": "உறுப்பினர்கள்",
    
    // OTP Page
    "otp.title": "OTP சரிபார்ப்பு",
    "otp.description": "உங்கள் பதிவு செய்யப்பட்ட மொபைலுக்கு OTP அனுப்பியுள்ளோம்",
    "otp.heading": "OTP உள்ளிடவும்",
    "otp.sentTo": "OTP அனுப்பப்பட்டது",
    "otp.resendIn": "மீண்டும் அனுப்ப",
    "otp.resend": "OTP மீண்டும் அனுப்பு",
    "otp.familyMembers": "குடும்ப உறுப்பினர்கள்",
    "otp.selectMember": "இந்த ரேஷன் ஆர்டரைப் பெறும் குடும்ப உறுப்பினரைத் தேர்ந்தெடுக்கவும்",
    "otp.memberSelected": "உறுப்பினர் ரேஷன் ஆர்டருக்கு தேர்ந்தெடுக்கப்பட்டார்",
    "otp.pleaseSelect": "தயவுசெய்து குடும்ப உறுப்பினரைத் தேர்ந்தெடுக்கவும்",
    "otp.confirm": "உறுதிப்படுத்து & தொடர",
    "otp.verifying": "சரிபார்க்கப்படுகிறது...",
    "otp.male": "ஆண்",
    "otp.female": "பெண்",
    "otp.years": "வயது",
    
    // Dashboard
    "dashboard.title": "டாஷ்போர்டு",
    "dashboard.welcome": "மீண்டும் வருக",
    "dashboard.members": "உறுப்பினர்கள்",
    "dashboard.backToLogin": "← உள்நுழைவுக்கு திரும்பு",
    "dashboard.availableItems": "கிடைக்கும் பொருட்கள்",
    "dashboard.deliveryTime": "டெலிவரி நேரம்",
    "dashboard.currentMonth": "தற்போதைய மாதம்",
    "dashboard.deliveryAddress": "டெலிவரி முகவரி",
    "dashboard.home": "வீடு",
    "dashboard.commodities": "கிடைக்கும் பொருட்கள்",
    "dashboard.allocation": "உங்கள் மாதாந்திர ஒதுக்கீடு மற்றும் நுகர்வு",
    "dashboard.available": "கிடைக்கும்",
    "dashboard.outOfStock": "கையிருப்பில் இல்லை",
    "dashboard.remaining": "மீதம்",
    "dashboard.selectProducts": "பொருட்களை தேர்ந்தெடுத்து ஆர்டர் செய்யுங்கள்",
    "dashboard.recentOrders": "சமீபத்திய ஆர்டர்கள்",
    "dashboard.purchaseHistory": "உங்கள் வாங்கல் வரலாறு",
    "dashboard.delivered": "டெலிவரி செய்யப்பட்டது",
    "dashboard.deliveryInfo": "டெலிவரி தகவல்",
    "dashboard.nextSlot": "அடுத்த கிடைக்கும் நேரம்",
    "dashboard.today": "இன்று",
    "dashboard.biometricRequired": "டெலிவரியில் பயோமெட்ரிக் சரிபார்ப்பு தேவை",
    "dashboard.secureDelivery": "கைரேகை அங்கீகாரத்துடன் பாதுகாப்பான டெலிவரி",
    
    // Product Selection
    "products.title": "பொருட்களை தேர்ந்தெடுக்கவும்",
    "products.description": "டெலிவரிக்கான பொருட்கள் மற்றும் அளவுகளை தேர்வு செய்யவும்",
    "products.quantity": "அளவு:",
    "products.default": "இயல்புநிலை:",
    "products.available": "கிடைக்கும்:",
    "products.orderSummary": "ஆர்டர் சுருக்கம்",
    "products.reviewItems": "உங்கள் தேர்ந்தெடுக்கப்பட்ட பொருட்களை மதிப்பாய்வு செய்யவும்",
    "products.noItems": "எந்த பொருளும் தேர்ந்தெடுக்கப்படவில்லை",
    "products.chooseProducts": "உங்கள் ஆர்டரில் சேர்க்க பொருட்களை தேர்வு செய்யவும்",
    "products.totalAmount": "மொத்த தொகை:",
    "products.proceedToPayment": "பணம் செலுத்துவதற்கு தொடரவும்",
    "products.highQuality": "தினசரி நுகர்வுக்கான உயர்தர அரிசி",
    "products.nutritious": "சத்தான முழு கோதுமை மாவு",
    "products.pureRefined": "தூய சுத்திகரிக்கப்பட்ட சர்க்கரை",
    "products.refinedPalm": "சமையலுக்கான சுத்திகரிக்கப்பட்ட பாமாயில்",
    "products.highProtein": "உயர் புரதம் தூர் பருப்பு",
    "products.iodized": "ஆரோக்கியத்திற்கான அயோடின் உப்பு",
    
    // Order Confirmation
    "order.title": "ஆர்டர் உறுதிப்படுத்தல்",
    "order.description": "உங்கள் ரேஷன் ஆர்டரை மதிப்பாய்வு செய்து உறுதிப்படுத்தவும்",
    "order.deliveryAddress": "டெலிவரி முகவரி",
    "order.selectTime": "டெலிவரி நேரத்தை தேர்ந்தெடுக்கவும்",
    "order.preferredSlot": "இன்றைய உங்கள் விருப்பமான டெலிவரி நேரத்தை தேர்வு செய்யவும்",
    "order.morning": "காலை",
    "order.afternoon": "மதியம்",
    "order.evening": "மாலை",
    "order.unavailable": "கிடைக்கவில்லை",
    "order.paymentMethod": "பணம் செலுத்தும் முறை",
    "order.paymentOption": "உங்கள் விருப்பமான பணம் செலுத்தும் விருப்பத்தை தேர்வு செய்யவும்",
    "order.upiPayment": "UPI பணம் செலுத்துதல்",
    "order.upiDescription": "UPI பயன்பாடுகளைப் பயன்படுத்தி செலுத்தவும்",
    "order.card": "டெபிட்/கிரெடிட் கார்டு",
    "order.cardDescription": "பாதுகாப்பான கார்டு பணம் செலுத்துதல்",
    "order.cash": "டெலிவரியில் பணம்",
    "order.cashDescription": "நீங்கள் பெறும்போது செலுத்தவும்",
    "order.biometricVerification": "பயோமெட்ரிக் சரிபார்ப்பு தேவை",
    "order.biometricDescription": "பாதுகாப்புக்காக, டெலிவரி உங்கள் வாசலுக்கு வரும்போது கைரேகை அங்கீகாரம் வழங்க வேண்டும்.",
    "order.biometricBenefit1": "அங்கீகரிக்கப்பட்ட பெறுநர்கள் மட்டுமே ரேஷன் பெறுவதை உறுதி செய்கிறது",
    "order.biometricBenefit2": "மோசடி மற்றும் அங்கீகரிக்கப்படாத அணுகலை தடுக்கிறது",
    "order.biometricBenefit3": "விரைவான மற்றும் பாதுகாப்பான சரிபார்ப்பு செயல்முறை",
    "order.orderSummary": "ஆர்டர் சுருக்கம்",
    "order.subtotal": "சப்டோட்டல்",
    "order.deliveryFee": "டெலிவரி கட்டணம் (தூரம் > 5கிமீ)",
    "order.total": "மொத்தம்",
    "order.confirmOrder": "ஆர்டரை உறுதிப்படுத்து",
    "order.processing": "ஆர்டர் செயல்படுத்தப்படுகிறது...",
    "order.protected": "உங்கள் ஆர்டர் அரசாங்க பாதுகாப்பால் பாதுகாக்கப்படுகிறது",
    "order.smsUpdates": "டெலிவரியில் SMS புதுப்பிப்புகளைப் பெறுவீர்கள்",
    
    // Tracking Page
    "tracking.title": "உங்கள் ஆர்டரை கண்காணிக்கவும்",
    "tracking.description": "நேரடி டெலிவரி புதுப்பிப்புகள்",
    "tracking.order": "ஆர்டர்",
    "tracking.deliveryProgress": "டெலிவரி முன்னேற்றம்",
    "tracking.onTheWay": "வழியில் உள்ளது",
    "tracking.readyForDelivery": "டெலிவரிக்கு தயாராக உள்ளது",
    "tracking.overallProgress": "ஒட்டுமொத்த முன்னேற்றம்",
    "tracking.orderConfirmed": "ஆர்டர் உறுதி செய்யப்பட்டது",
    "tracking.orderConfirmedDesc": "உங்கள் ஆர்டர் உறுதி செய்யப்பட்டு தயாரிக்கப்படுகிறது",
    "tracking.itemsPrepared": "பொருட்கள் தயாரிக்கப்பட்டன",
    "tracking.itemsPreparedDesc": "அனைத்து பொருட்களும் பேக் செய்யப்பட்டு அனுப்புவதற்கு தயாராக உள்ளன",
    "tracking.outForDelivery": "டெலிவரிக்கு புறப்பட்டது",
    "tracking.outForDeliveryDesc": "டெலிவரி ஏஜென்ட் உங்கள் இடத்திற்கு வழியில் உள்ளார்",
    "tracking.biometricVerification": "பயோமெட்ரிக் சரிபார்ப்பு",
    "tracking.biometricDesc": "பாதுகாப்பான டெலிவரிக்கான கைரேகை சரிபார்ப்புக்கு காத்திருக்கிறது",
    "tracking.expected": "எதிர்பார்க்கப்படுகிறது:",
    "tracking.enRoute": "டெலிவரிக்கு வழியில்",
    "tracking.liveLocation": "நேரடி இருப்பிடம்",
    "tracking.vehicleLocation": "டெலிவரி வாகன இருப்பிடம்",
    "tracking.approximately": "தோராயமாக",
    "tracking.away": "தூரம்",
    "tracking.eta": "ETA:",
    "tracking.minutes": "நிமிடங்கள்",
    "tracking.deliveryAgent": "டெலிவரி ஏஜென்ட்",
    "tracking.contact": "தொடர்பு:",
    "tracking.vehicle": "வாகனம்:",
    "tracking.orderDetails": "ஆர்டர் விவரங்கள்",
    "tracking.totalPaid": "மொத்தம் செலுத்தப்பட்டது",
    "tracking.paymentMethod": "பணம் செலுத்தும் முறை:",
    "tracking.biometricSecurity": "பயோமெட்ரிக் பாதுகாப்பு",
    "tracking.secureDelivery": "ஏஜென்ட் வரும்போது கைரேகை சரிபார்ப்பு தேவைப்படும் பாதுகாப்பான டெலிவரி.",
    "tracking.preventsUnauthorized": "அங்கீகரிக்கப்படாத அணுகலைத் தடுக்கிறது",
    "tracking.ensuresRecipient": "சரியான பெறுநரை உறுதி செய்கிறது",
    "tracking.quickVerification": "விரைவான சரிபார்ப்பு செயல்முறை",
    "tracking.readyForVerification": "சரிபார்ப்புக்கு தயார்",
    "tracking.downloadReceipt": "ரசீதைப் பதிவிறக்கவும்",
    "tracking.returnToDashboard": "டாஷ்போர்டுக்குத் திரும்பு",
    
    // Product Names
    "product.rice": "பிரீமியம் அரிசி",
    "product.wheat": "முழு கோதுமை",
    "product.sugar": "சுத்திகரிக்கப்பட்ட சர்க்கரை",
    "product.oil": "பாமாயில்",
    "product.dhal": "தூர் பருப்பு",
    "product.salt": "அயோடின் உப்பு",
  }
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};